name: Deploy NodeJs Application To Server


on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd /root/NodeJS-deploy-with-CI-CD-Github-Actions-
            git pull
            docker compose up -d --build